name: NIckName
version: '1.0-SNAPSHOT'
main: io.zlero.nIckName.NicknamePlugin
api-version: '1.20'
commands:
  닉네임:
    description: 유저의 닉네임을 변경
    usage: /<command> <유저> <닉네임>
    permission: nickname.admin
  닉네임설정:
    description: 유저가 닉네임을 설정하는 GUI 열기
    usage: /<command>
  닉네임초기화:
    description: 유저의 닉네임을 초기화
    usage: /<command> <유저>
    permission: nickname.admin
  닉네임저장:
    description: 닉네임 데이터를 저장
    usage: /<command>
    permission: nickname.admin